#!/usr/bin/env bash

set -e

. script/env_setup

curl -X DELETE "${ELASTICSEARCH_URL}/music"
echo

curl -X PUT "${ELASTICSEARCH_URL}/music" -d '{
    "settings": {
        "number_of_shards": 1,
        "analysis": {
            "filter": {
                "autocomplete_filter": {
                    "type": "edge_ngram",
                    "min_gram": 1,
                    "max_gram": 20
                }
            },
            "analyzer": {
                "folding": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [
                        "lowercase",
                        "asciifolding"
                    ]
                },
                "autocomplete": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [
                        "lowercase",
                        "asciifolding",
                        "autocomplete_filter"
                    ]
                }
            }
        }
    },
    "mappings": {
        "album": {
            "properties": {
                "title": {
                    "type": "string",
                    "analyzer":  "autocomplete",
                    "index_analyzer":  "autocomplete",
                    "search_analyzer": "folding"
                },
                "artist_ngram": {
                    "type": "string",
                    "analyzer":  "autocomplete",
                    "index_analyzer":  "autocomplete",
                    "search_analyzer": "folding"
                },
                "artist": {
                    "type": "string"
                },
                "year": {
                    "type": "integer",
                    "analyzer":  "autocomplete",
                    "index_analyzer":  "autocomplete",
                    "search_analyzer": "folding"
                }
            }
        }
    }

}'

./script/import_all_docs
